"""
Supplementary mod catalogues (ADR-0009).

Your `mod_downloads.json` is generated by Infinity Mod Forge and carries one
URL per mod. The community keeps richer, curated databases - notably the
La Couronne de Cuivre list at https://github.com/RiwsPy/lcc-docs (MIT), whose
`db/mods.json` holds ~2,100 mods with their tp2 name, every known download URL,
a maintenance status and a quality rating.

Used here for two things:

  * **resolution fallback** - when the manifest entry cannot be resolved, look
    the mod up by its tp2 and try the URLs the catalogue knows about. As with
    ADR-0008 this yields a CANDIDATE: the archive still has to contain
    `<folder>.tp2` before anything is installed;
  * **advisory metadata** - surface mods the catalogue marks obsolete, missing,
    beta or "avoid", which is information the download manifest simply does not
    carry.

The catalogue is read from a path you supply. It is never bundled and never
fetched automatically: it is third-party data with its own licence and its own
release cadence.
"""
import json
import os
from dataclasses import dataclass, field
from typing import Dict, Iterable, List, Optional, Sequence

from .errors import ConfigError
from .urls import repo_from_url
from .naming import normalize_key

# LCC `safe` ratings, from its settings.py
SAFE_LABELS = {2: "quality mod", 1: "may cause problems", 0: "avoid or obsolete"}
CONCERNING_STATUS = {"obsolete", "missing", "unreleased", "wip"}
# Extensions this tool can actually extract. `.exe` is deliberately absent:
# a self-extracting installer needs --allow-exe and is never auto-selected.
DIRECT_EXT = (".iemod", ".zip", ".7z", ".rar", ".tar", ".tar.gz", ".tgz",
              ".tar.bz2", ".tar.xz")
NOTABLE_STATUS = CONCERNING_STATUS | {"beta", "archived"}
_MAX_BYTES = 64 * 1024 * 1024


@dataclass(frozen=True)
class CatalogueEntry:
    tp2: str
    name: str
    urls: tuple = ()
    safe: Optional[int] = None
    status: tuple = ()
    last_update: Optional[str] = None
    games: tuple = ()
    categories: tuple = ()
    requires: tuple = ()
    conflicts: tuple = ()
    embedded_in: Optional[int] = None
    origin: str = "catalogue"

    @property
    def github(self) -> Optional[str]:
        """The repository that best matches this mod, if the catalogue lists one."""
        repos = [r for r in (repo_from_url(u) for u in self.urls) if r]
        if not repos:
            return None
        key = normalize_key(self.tp2)
        exact = [r for r in repos if normalize_key(r.split("/", 1)[1]) == key]
        if exact:
            return exact[0]
        partial = [r for r in repos if key and key in normalize_key(r.split("/", 1)[1])]
        return partial[0] if partial else repos[0]

    @property
    def http_urls(self) -> tuple:
        # The catalogue keeps known-dead links on record but does not offer them;
        # its own page suppresses the links of a "missing" mod. Trying them would
        # only produce a confusing 404 for something already known to be gone.
        if "missing" in self.status:
            return ()
        return tuple(u for u in self.urls if u.startswith(("https://", "http://")))

    @property
    def direct_urls(self) -> tuple:
        """
        URLs that ARE the mod archive rather than a page describing it.

        The catalogue marks these itself (it renders a padlock next to them);
        ~12% of its mods have one. They are the best thing it can give us: no
        API call, no page to scrape, no ambiguity about which asset is meant.
        """
        import urllib.parse

        out = []
        for url in self.http_urls:
            path = urllib.parse.urlsplit(url).path.lower()
            if path.endswith(DIRECT_EXT):
                out.append(url)
        return tuple(out)

    @property
    def expected_tp2(self) -> Optional[str]:
        """
        The .tp2 name this mod actually ships, when the catalogue records a
        usable one.

        This is the field that knows `Reflections of Destiny` installs as
        `Reflections_of_Destiny`, not as the `Reflections` your WeiDU.log
        remembers. Entries whose `tp2` is really a display name ("NSC
        Portraits") are rejected: a tp2 has no spaces.
        """
        value = (self.tp2 or "").strip()
        if not value or " " in value or "/" in value or "\\" in value:
            return None
        return value

    @property
    def is_outdated(self) -> bool:
        """
        The catalogue's own staleness rule (models/mod.py in lcc-docs).

        EE 2.0 shipped in April 2016 and EE 2.6 in April 2021; an EE mod last
        touched before those dates is very likely incompatible with a current
        install - interface mods especially, since 2.6 changed the UI.
        """
        if not self.last_update or not any(
                g in self.games for g in ("BGEE", "SoD", "BG2EE", "EET", "IWDEE", "PSTEE")):
            return False
        if self.last_update < "2016-04-01":
            return True
        interface = any("nterface" in c for c in self.categories)
        return interface and self.last_update < "2021-04-01"

    def advisories(self) -> List[str]:
        """Human-readable warnings this catalogue raises about the mod."""
        notes = []
        if self.embedded_in:
            notes.append(
                f"{self.origin}: this mod is already included in another mod "
                f"(catalogue id {self.embedded_in}) - installing both may conflict")
        if self.is_outdated:
            notes.append(
                f"{self.origin}: last updated {self.last_update}, before the "
                f"Enhanced Edition patch that changed what it hooks into")
        if self.safe == 0:
            notes.append(f"{self.origin} rates this mod '{SAFE_LABELS[0]}'")
        elif self.safe == 1:
            notes.append(f"{self.origin} rates this mod '{SAFE_LABELS[1]}'")
        flagged = sorted(set(self.status) & NOTABLE_STATUS)
        if flagged:
            notes.append(f"{self.origin} status: {', '.join(flagged)}"
                         + (f" (last updated {self.last_update})" if self.last_update else ""))
        return notes

    def game_advisories(self, game: Optional[str]) -> List[str]:
        """
        Warn when the catalogue does not list this mod for the game being built.

        Deliberately silent when the game is unknown or the catalogue lists no
        games at all: an unfounded incompatibility warning on a 148-mod install
        is noise that trains you to ignore the real ones.
        """
        if not game or not self.games:
            return []
        if game in self.games:
            return []
        return [f"{self.origin} does not list this mod as {game}-compatible "
                f"(it lists: {', '.join(self.games)})"]

    @property
    def blocking(self) -> bool:
        return self.safe == 0 or bool(set(self.status) & CONCERNING_STATUS)


@dataclass
class SupplementaryCatalogue:
    by_key: Dict[str, List[CatalogueEntry]] = field(default_factory=dict)
    by_repo: Dict[str, CatalogueEntry] = field(default_factory=dict)
    name: str = "catalogue"
    skipped: int = 0

    # ------------------------------------------------------------- loading
    @classmethod
    def load(cls, path: str) -> "SupplementaryCatalogue":
        try:
            if os.path.getsize(path) > _MAX_BYTES:
                raise ConfigError(f"catalogue {path} is larger than {_MAX_BYTES} bytes")
            with open(path, "r", encoding="utf-8") as fh:
                raw = json.load(fh)
        except OSError as exc:
            raise ConfigError(f"cannot read catalogue {path}: {exc}") from exc
        except json.JSONDecodeError as exc:
            raise ConfigError(f"catalogue {path} is not valid JSON: {exc}") from exc
        return cls.from_entries(raw, name=os.path.basename(path))

    @classmethod
    def from_entries(cls, raw, name: str = "catalogue") -> "SupplementaryCatalogue":
        if isinstance(raw, dict):
            raw = raw.get("mods", raw.get("entries", []))
        if not isinstance(raw, list):
            raise ConfigError(f"{name}: expected a JSON array of mods")

        catalogue = cls(name=name)
        for item in raw:
            if not isinstance(item, dict):
                catalogue.skipped += 1
                continue
            tp2 = str(item.get("tp2") or "").strip()
            # 'non-weidu' marks entries that are not WeiDU mods at all.
            if not tp2 or tp2.lower() == "non-weidu":
                catalogue.skipped += 1
                continue
            folder = tp2.replace("\\", "/").split("/")[0]
            key = normalize_key(folder)
            if not key:
                catalogue.skipped += 1
                continue

            urls = item.get("urls") or []
            entry = CatalogueEntry(
                tp2=folder,
                name=str(item.get("name") or folder),
                urls=tuple(u for u in urls if isinstance(u, str)),
                safe=item.get("safe") if isinstance(item.get("safe"), int) else None,
                status=tuple(s for s in (item.get("status") or []) if isinstance(s, str)),
                last_update=item.get("last_update") or None,
                games=tuple(g for g in (item.get("games") or []) if isinstance(g, str)),
                categories=tuple(c for c in (item.get("categories") or [])
                                 if isinstance(c, str)),
                embedded_in=(item.get("embedded_in")
                             if isinstance(item.get("embedded_in"), int) else None),
                requires=tuple((item.get("compatibilities") or {}).get("requires") or ()),
                conflicts=tuple((item.get("compatibilities") or {}).get("conflicts") or ()),
                origin=name,
            )
            catalogue.by_key.setdefault(key, []).append(entry)
            # A mod is also findable by the repository it lives in, which is how
            # an entry gets found when neither the WeiDU folder nor the manifest
            # key matches its catalogue tp2.
            for url in entry.urls:
                repo = repo_from_url(url)
                if repo:
                    catalogue.by_repo.setdefault(repo.lower(), entry)
        return catalogue

    def __len__(self) -> int:
        return sum(len(v) for v in self.by_key.values())

    # ------------------------------------------------------------- lookup
    def lookup(self, *candidates: Optional[str]) -> Optional[CatalogueEntry]:
        """Find an entry by any of the given names (mod folder, manifest key…)."""
        for candidate in candidates:
            if not candidate:
                continue
            entries = self.by_key.get(normalize_key(candidate))
            if entries:
                # A resolvable entry beats a bare forum link.
                with_repo = [e for e in entries if e.github]
                return (with_repo or entries)[0]
        return None

    def lookup_repo(self, repo: Optional[str]) -> Optional[CatalogueEntry]:
        """Find an entry by the GitHub repository it is published from."""
        return self.by_repo.get(repo.lower()) if repo else None


class CatalogueSet:
    """Several catalogues consulted in order; the first hit wins."""

    def __init__(self, catalogues: Sequence[SupplementaryCatalogue] = ()):
        self.catalogues = list(catalogues)

    @classmethod
    def load(cls, paths: Iterable[str]) -> "CatalogueSet":
        return cls([SupplementaryCatalogue.load(p) for p in paths or ()])

    def __bool__(self) -> bool:
        return bool(self.catalogues)

    def __len__(self) -> int:
        return sum(len(c) for c in self.catalogues)

    def lookup(self, *candidates: Optional[str]) -> Optional[CatalogueEntry]:
        for catalogue in self.catalogues:
            hit = catalogue.lookup(*candidates)
            if hit:
                return hit
        return None

    def lookup_repo(self, repo: Optional[str]) -> Optional[CatalogueEntry]:
        for catalogue in self.catalogues:
            hit = catalogue.lookup_repo(repo)
            if hit:
                return hit
        return None

    def find(self, folder=None, key=None, repo=None) -> Optional[CatalogueEntry]:
        """Folder, then manifest key, then the repository the manifest names."""
        return self.lookup(folder, key) or self.lookup_repo(repo)
